# .github/workflows/install-snowsql/action.yml
name: 'Install SnowSQL'
description: 'Sets up snowsql'

runs:
  using: 'composite'
  steps:
    - name: Install SnowSQL
      shell: bash
      run: |        
        wget https://sfc-repo.snowflakecomputing.com/snowsql/bootstrap/1.4/linux_x86_64/snowflake-snowsql-1.4.2-1.x86_64.rpm
        sudo dnf install ./snowflake-snowsql-1.4.2-1.x86_64.rpm
        echo "/usr/bin/snowsql" >> $GITHUB_PATH

    - name: Check SnowSQL installation
      shell: bash
      run: |
        echo "snowsql version:"
        snowsql -v