# .github/workflows/setup-snowflake-key/action.yml
name: 'Setup Snowflake Key'
description: 'Sets up pem for Snowflake'

runs:
  using: 'composite'
  steps:        
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ env.AWS_SESSION_TOKEN }}
        aws-region: us-east-1
          
    - name: Get Snowflake private key from AWS Secrets Manager
      shell: bash
      run: |
        aws secretsmanager get-secret-value \
          --secret-id asmith_snowflake_pem \
          --query SecretString \
          --output text > snowflake_key.pem
        chmod 600 snowflake_key.pem      
